module instance_init
!---------------------------------------------------------------
!   This module is used for init cpl instance meta data
!   ie. timeMeta, and this code must be generated by BCGen
!---------------------------------------------------------------
use time_def
use global_var, only : time_meta
implicit none
    public :: timeMeta_init

contains

subroutine timeMeta_init(time_meta, ierr)
    implicit  none
    type(timeMeta),    intent(inout) :: time_meta
    integer, optional, intent(inout) :: ierr 

end subroutine timeMeta_init 




end module instance_init
