# CMake generated Testfile for 
# Source directory: /share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general
# Build directory: /share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(init_finialize_1_proc "/usr/local/bin/mpiexec" "-n" "1" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_init_finalize")
set_tests_properties(init_finialize_1_proc PROPERTIES  TIMEOUT "480")
add_test(init_finialize_2_proc "/usr/local/bin/mpiexec" "-n" "2" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_init_finalize")
set_tests_properties(init_finialize_2_proc PROPERTIES  TIMEOUT "480")
add_test(init_finalize_2_proc_with_args "/usr/local/bin/mpiexec" "-n" "2" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_init_finalize" "--pio-tf-stride=2" "--pio-tf-num-aggregators=2")
set_tests_properties(init_finalize_2_proc_with_args PROPERTIES  TIMEOUT "480")
add_test(pio_file_simple_tests "/usr/local/bin/mpiexec" "-n" "2" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_file_simple_tests")
set_tests_properties(pio_file_simple_tests PROPERTIES  TIMEOUT "480")
add_test(pio_file_fail "/usr/local/bin/mpiexec" "-n" "2" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_file_fail")
set_tests_properties(pio_file_fail PROPERTIES  TIMEOUT "480")
add_test(ncdf_simple_tests "/usr/local/bin/mpiexec" "-n" "2" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/ncdf_simple_tests")
set_tests_properties(ncdf_simple_tests PROPERTIES  TIMEOUT "480")
add_test(ncdf_get_put_1proc "/usr/local/bin/mpiexec" "-n" "1" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/ncdf_get_put")
set_tests_properties(ncdf_get_put_1proc PROPERTIES  TIMEOUT "480")
add_test(ncdf_get_put_2proc "/usr/local/bin/mpiexec" "-n" "2" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/ncdf_get_put")
set_tests_properties(ncdf_get_put_2proc PROPERTIES  TIMEOUT "480")
add_test(ncdf_fail "/usr/local/bin/mpiexec" "-n" "2" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/ncdf_fail")
set_tests_properties(ncdf_fail PROPERTIES  TIMEOUT "480")
add_test(ncdf_inq "/usr/local/bin/mpiexec" "-n" "2" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/ncdf_inq")
set_tests_properties(ncdf_inq PROPERTIES  TIMEOUT "480")
add_test(pio_rearr "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_rearr")
set_tests_properties(pio_rearr PROPERTIES  TIMEOUT "480")
add_test(pio_rearr_opts "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_rearr_opts")
set_tests_properties(pio_rearr_opts PROPERTIES  TIMEOUT "480")
add_test(pio_rearr_opts2_1p "/usr/local/bin/mpiexec" "-n" "1" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_rearr_opts2")
set_tests_properties(pio_rearr_opts2_1p PROPERTIES  TIMEOUT "480")
add_test(pio_rearr_opts2_3p "/usr/local/bin/mpiexec" "-n" "3" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_rearr_opts2")
set_tests_properties(pio_rearr_opts2_3p PROPERTIES  TIMEOUT "480")
add_test(pio_rearr_opts2_4p "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_rearr_opts2")
set_tests_properties(pio_rearr_opts2_4p PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_1p "/usr/local/bin/mpiexec" "-n" "1" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests")
set_tests_properties(pio_decomp_tests_1p PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_2p "/usr/local/bin/mpiexec" "-n" "2" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests")
set_tests_properties(pio_decomp_tests_2p PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_3p "/usr/local/bin/mpiexec" "-n" "3" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests")
set_tests_properties(pio_decomp_tests_3p PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_4p_1agg "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests" "--pio-tf-num-aggregators=1")
set_tests_properties(pio_decomp_tests_4p_1agg PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_4p_2agg "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests" "--pio-tf-num-aggregators=2")
set_tests_properties(pio_decomp_tests_4p_2agg PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_4p_3agg "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests" "--pio-tf-num-aggregators=3")
set_tests_properties(pio_decomp_tests_4p_3agg PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_4p_1iop "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests" "--pio-tf-num-io-tasks=1")
set_tests_properties(pio_decomp_tests_4p_1iop PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_4p_2iop "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests" "--pio-tf-num-io-tasks=2")
set_tests_properties(pio_decomp_tests_4p_2iop PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_4p_3iop "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests" "--pio-tf-num-io-tasks=3")
set_tests_properties(pio_decomp_tests_4p_3iop PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_4p_2iop_2str "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests" "--pio-tf-num-io-tasks=2" "--pio-tf-stride=2")
set_tests_properties(pio_decomp_tests_4p_2iop_2str PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_4p_2iop_1agg "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests" "--pio-tf-num-io-tasks=2" "--pio-tf-num-aggregators=1")
set_tests_properties(pio_decomp_tests_4p_2iop_1agg PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_1d_1p "/usr/local/bin/mpiexec" "-n" "1" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_1d")
set_tests_properties(pio_decomp_tests_1d_1p PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_1d_2p "/usr/local/bin/mpiexec" "-n" "2" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_1d")
set_tests_properties(pio_decomp_tests_1d_2p PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_1d_3p "/usr/local/bin/mpiexec" "-n" "3" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_1d")
set_tests_properties(pio_decomp_tests_1d_3p PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_1d_4p_1agg "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_1d" "--pio-tf-num-aggregators=1")
set_tests_properties(pio_decomp_tests_1d_4p_1agg PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_1d_4p_2agg "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_1d" "--pio-tf-num-aggregators=2")
set_tests_properties(pio_decomp_tests_1d_4p_2agg PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_1d_4p_3agg "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_1d" "--pio-tf-num-aggregators=3")
set_tests_properties(pio_decomp_tests_1d_4p_3agg PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_1d_4p_1iop "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_1d" "--pio-tf-num-io-tasks=1")
set_tests_properties(pio_decomp_tests_1d_4p_1iop PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_1d_4p_2iop "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_1d" "--pio-tf-num-io-tasks=2")
set_tests_properties(pio_decomp_tests_1d_4p_2iop PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_1d_4p_3iop "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_1d" "--pio-tf-num-io-tasks=3")
set_tests_properties(pio_decomp_tests_1d_4p_3iop PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_1d_4p_2iop_2str "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_1d" "--pio-tf-num-io-tasks=2" "--pio-tf-stride=2")
set_tests_properties(pio_decomp_tests_1d_4p_2iop_2str PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_1d_4p_2iop_1agg "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_1d" "--pio-tf-num-io-tasks=2" "--pio-tf-num-aggregators=1")
set_tests_properties(pio_decomp_tests_1d_4p_2iop_1agg PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_2d_1p "/usr/local/bin/mpiexec" "-n" "1" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_2d")
set_tests_properties(pio_decomp_tests_2d_1p PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_2d_2p "/usr/local/bin/mpiexec" "-n" "2" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_2d")
set_tests_properties(pio_decomp_tests_2d_2p PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_2d_3p "/usr/local/bin/mpiexec" "-n" "3" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_2d")
set_tests_properties(pio_decomp_tests_2d_3p PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_2d_4p_1agg "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_2d" "--pio-tf-num-aggregators=1")
set_tests_properties(pio_decomp_tests_2d_4p_1agg PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_2d_4p_2agg "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_2d" "--pio-tf-num-aggregators=2")
set_tests_properties(pio_decomp_tests_2d_4p_2agg PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_2d_4p_3agg "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_2d" "--pio-tf-num-aggregators=3")
set_tests_properties(pio_decomp_tests_2d_4p_3agg PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_2d_4p_1iop "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_2d" "--pio-tf-num-io-tasks=1")
set_tests_properties(pio_decomp_tests_2d_4p_1iop PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_2d_4p_2iop "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_2d" "--pio-tf-num-io-tasks=2")
set_tests_properties(pio_decomp_tests_2d_4p_2iop PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_2d_4p_3iop "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_2d" "--pio-tf-num-io-tasks=3")
set_tests_properties(pio_decomp_tests_2d_4p_3iop PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_2d_4p_2iop_2str "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_2d" "--pio-tf-num-io-tasks=2" "--pio-tf-stride=2")
set_tests_properties(pio_decomp_tests_2d_4p_2iop_2str PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_2d_4p_2iop_1agg "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_2d" "--pio-tf-num-io-tasks=2" "--pio-tf-num-aggregators=1")
set_tests_properties(pio_decomp_tests_2d_4p_2iop_1agg PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_3d_1p "/usr/local/bin/mpiexec" "-n" "1" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_3d")
set_tests_properties(pio_decomp_tests_3d_1p PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_3d_2p "/usr/local/bin/mpiexec" "-n" "2" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_3d")
set_tests_properties(pio_decomp_tests_3d_2p PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_3d_3p "/usr/local/bin/mpiexec" "-n" "3" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_3d")
set_tests_properties(pio_decomp_tests_3d_3p PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_3d_4p_1agg "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_3d" "--pio-tf-num-aggregators=1")
set_tests_properties(pio_decomp_tests_3d_4p_1agg PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_3d_4p_2agg "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_3d" "--pio-tf-num-aggregators=2")
set_tests_properties(pio_decomp_tests_3d_4p_2agg PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_3d_4p_3agg "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_3d" "--pio-tf-num-aggregators=3")
set_tests_properties(pio_decomp_tests_3d_4p_3agg PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_3d_4p_1iop "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_3d" "--pio-tf-num-io-tasks=1")
set_tests_properties(pio_decomp_tests_3d_4p_1iop PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_3d_4p_2iop "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_3d" "--pio-tf-num-io-tasks=2")
set_tests_properties(pio_decomp_tests_3d_4p_2iop PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_3d_4p_3iop "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_3d" "--pio-tf-num-io-tasks=3")
set_tests_properties(pio_decomp_tests_3d_4p_3iop PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_3d_4p_2iop_2str "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_3d" "--pio-tf-num-io-tasks=2" "--pio-tf-stride=2")
set_tests_properties(pio_decomp_tests_3d_4p_2iop_2str PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_tests_3d_4p_2iop_1agg "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_tests_3d" "--pio-tf-num-io-tasks=2" "--pio-tf-num-aggregators=1")
set_tests_properties(pio_decomp_tests_3d_4p_2iop_1agg PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_frame_tests "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_frame_tests")
set_tests_properties(pio_decomp_frame_tests PROPERTIES  TIMEOUT "480")
add_test(pio_decomp_fillval "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_decomp_fillval")
set_tests_properties(pio_decomp_fillval PROPERTIES  TIMEOUT "480")
add_test(pio_iosystem_tests "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_iosystem_tests")
set_tests_properties(pio_iosystem_tests PROPERTIES  TIMEOUT "480")
add_test(pio_iosystem_tests2 "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_iosystem_tests2")
set_tests_properties(pio_iosystem_tests2 PROPERTIES  TIMEOUT "480")
add_test(pio_iosystem_tests3 "/usr/local/bin/mpiexec" "-n" "4" "/share/BCGen/develDir/BCGenV2.1/BCGen/baseCpl/src/depUtils/ParallelIO/tests/general/pio_iosystem_tests3")
set_tests_properties(pio_iosystem_tests3 PROPERTIES  TIMEOUT "480")
