FC = mpif90
include ./Makefile.conf
models=$(shell ls -l ./models | grep ^d|grep -v 'cpl'|awk '{print $$9}')

.PHONY : all models deps
all : main

main : models
	echo "Make main..."; \
	cd ./models/cpl; \
	make; \
	mv main ../../bin; \
	cd -;

models : deps
	echo "Make models..."; \
	for dir in $(models);\
	do\
		echo $$dir; \
		cd ./models/$$dir; \
		make; \
		cd -; \
	done
	
deps : 
	echo "Make deps..."; \
	cd ./deps; \
	make; \
	cd -;
